version: '3.7'

services:
  streamsheets-service-streams:
    depends_on:
      - mongodb
  mongodb:
    image: mongo:3.6
    container_name: database
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: cedalo
    #   MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    expose:
      - 27017
    networks:
      - streamsheets
    logging:
      driver: "none"
networks:
  streamsheets:
    external:
      name: streamsheets
